name: structure_base
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #  저장
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1
  uuid: ^3.0.7

  # 상태관리
  flutter_riverpod: 2.3.7
  riverpod_annotation: 2.1.2
  hooks_riverpod: ^2.3.7

  # utils
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^1.3.0
  go_router: ^6.5.8
  http: ^0.13.5
  dio: ^5.1.2
  url_launcher: ^6.1.11
  path_to_regexp: ^0.4.0
  flutter_screenutil: ^5.7.0

#  기기정보
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  flutter_udid: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  mockito: ^5.3.2
  freezed: ^2.3.5
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  riverpod_generator: 2.2.6
  logging: 1.1.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
